### ISSUE TITLE
Rename to app-route

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/app-route#100]
It is time.

We've gotten continual and well-reasoned [feedback](https://twitter.com/joshlangner/status/724946431027601408) that the periodic-table element naming scheme is cute but very confusing, especially for new developers coming to Polymer and the components.

Since the "carbon" elements are a new product line and really all about building apps, let's just call them what they are: the app-* elements.

Question: this should probably warrant a major version bump?

Task list (added by rictic):
- [x] rename in this repo's source code
- [x] rename the repo itself
- [x] stamp v0.9.0
- [x] update the docs repo
- [x] update the blog post

**Comment by abdonrd** [comment]
Wow! Nice news!

**Comment by rictic** [comment]
Yay!

If we rename the repo (and I think we should) then this does require a major version bump to prevent breaking existing users, so we can call the app-router release `v0.9.0`. At the same time, we're taking a look at PR #77 around this weekend which is a (small) breaking change as well.

Do we have a date before which we want to land this rename? Doing two major version bumps wouldn't be much of a problem if the rename needs to land quick.

**Comment by tjsavage** [comment]
Agreed on bumping to 0.9.

Let's try to land this rename early next week, so if that can coincide with the other breaking change that'd be perfect.

**Comment by atomikolex** [comment]
There already is Erik Ringsmuth's [https://github.com/erikringsmuth/app-router](url)... Just saying.

**Comment by abdonrd** [comment]
@atomikolex Well, change one character... `PolymerElements/app-route` vs `erikringsmuth/app-router` 😅

**Comment by atomikolex** [comment]
Sure thing. Just thought the similarity may actually enhance confusion for older users. 

Also, as this namespace falls in line with the app-layout lab elements, it may be difficult to understand why all of these new elements would be all about building apps - compared to the paper, neon, gold, or platinum elements. 

If you are breaking your naming system in order to respond to the above feedback, maybe you should do a full reshuffle across all element lines, and strip the abstractness and fragmentation of the current system. Why not model a new system on a short and catchy namespace, like Angular's -ng?

**Comment by tjsavage** [comment]
@atomikolex Agreed, a full reshuffle is probably the goal, to get more concrete and less abstract. It would be a big catalog-wide breaking change though, so this current plan is a bit to test the waters with changing a single name of a new element and also introduce some forthcoming new elements with the app-* name. If it works out, we'll be able to have a little more data and be able to plan a better more for a larger rename.

**Comment by atomikolex** [comment]
As always, I am sure you will come up with a good solution, if you need to make that change. For a big overhaul, my vote would be for a unified system, taking in the Polymer brand somehow.

**Comment by gaurav21r** [comment]
This should be closed? @rictic

**Comment by rictic** [comment]
Yep!
