### ISSUE TITLE
Please tell me why it requires a slash at the end?

### ISSUE THREAD

**Issue by sergofan** [PolymerElements/app-route#106]
As here - [https://jsbin.com/kotahidovu/edit?html,console,output](url)
like the:
`if (this.route.path === '/two') {
  this.set('route.path', '/two/');
};`
Otherwise, why it does not work.
This is a bug or a feature? :-)
Maybe I do not understand something?
Thanks.

**Comment by TimvdLippe** [comment]
This should be fixed in #77. It was required to be able to update the url on a sub-route if the data-binding changed. If you would omit the `/`, the sub-route would not be active and therefore the data-binding update would be discarded.

**Comment by sergofan** [comment]
Ok.  :-)
