### ISSUE TITLE
app-route recurses when query params have a single quote

### ISSUE THREAD

**Issue by nik3daz** [PolymerElements/app-route#117]
### Description
Having a single quote in a query param causes 'Maximum call stack size exceeded' to be spewed into the console. Other symbols don't seem to exhibit this behavior.

### Expected outcome
app-route is able to handle queries with quotes.

### Actual outcome
![app-route-stack-exceeded](https://cloud.githubusercontent.com/assets/1677402/16069392/703a13ca-3311-11e6-8782-a5098d1869c3.png)

### Live Demo
https://elements.polymer-project.org/bower_components/app-route/demo/?state=paused&time=1'#/video/_wYtG7aQTHA

### Steps to reproduce
1. Go to link above with the console open
2. Press the time button
3. Console is spammed with 'Maximum call stack size exceeded'

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by rictic** [comment]
This is probably https://github.com/PolymerElements/iron-location/issues/36

**Comment by rictic** [comment]
The fix is landing soon! Sorry for the delay. Testing Safari is always an adventure.

**Comment by rictic** [comment]
Fix landed upstream last week with iron-location v0.8.6
