### ISSUE TITLE
'use strict' failing closure compile

### ISSUE THREAD

**Issue by nik3daz** [PolymerElements/app-route#118]
### Description
The 'use strict' line at the top of all app-route elements is causing closure compile failure. This can be fixed by wrapping the entire script so it looks like

```
(function() {
'use strict'
....
}());
```

### Steps to reproduce

When attempting to add app-route to a Chromium closure build (e.g chrome/browser/resources/md_history/compiled_resources2.gyp), the closure build fails with
```
## ERROR - Suspicious code. Is there a missing '+' on the previous line?
## 'use strict';
## ^
```

**Comment by cdata** [comment]
Thanks for reporting, I'll take a look.

**Comment by rictic** [comment]
I suspect this is caused by combining together JS from multiple files before passing it to the compiler. Is that correct?

It seems like this is a bug in the code that's combining the JS. Do you know what tool it is?
