### ISSUE TITLE
[bug] some styles not work in pages

### ISSUE THREAD

**Issue by AliMD** [PolymerElements/app-route#121]
I'm not sure but i think this bug related to app-route
Some css not work in pages

example:
in `app-layout-templates` when use a paper-card in child views, some default css not work
in this case elevation styles not generated in router view but it work fine in main app file

![screen shot 2016-06-21 at 5 05 33 am](https://cloud.githubusercontent.com/assets/697913/16214477/fa473858-376d-11e6-87ae-91da2fe9a287.png)

no matter shaddy-dom or shadow-dom  or event what browser!

temporary solution:
import paper-card in root not router child views

**Comment by abdonrd** [comment]
The problem:
- https://github.com/Polymer/app-drawer-template/issues/19
- https://github.com/Polymer/polymer/issues/3705

**Comment by AliMD** [comment]
@abdonrd Thank you, it's not related to app-route ?

**Comment by abdonrd** [comment]
@AliMD no, I think is a Polymer issue. :9
