### ISSUE TITLE
Relative links don't navigate with `app-location` and `use-hash-as-path`

### ISSUE THREAD

**Issue by intcreatorlds** [PolymerElements/app-route#130]
### Description

When I use the attribute `use-hash-as-path` in `<app-route>`, when relative links are clicked the URL is modified but the page does not navigate.

Using `app-location` and `app-route`:

    <app-location route="{{route}}" use-hash-as-path></app-location>
    <app-route
      route="{{route}}"
      pattern="/:page"
      data="{{data}}">
    </app-route>
    <iron-ajax
      id="my-ajax"
      handle-as="json"
      on-response="loadData"
      on-error="showError"
      debounce-duration="300">
    </iron-ajax>

A typical link on the page:

    <a class="tag" href$="../landing#search=[[item]]">[[item]]</a>

URL of the page I'm on: `/ask/myPage#/4`

URL of the page the example link should take me to: `/ask/landing#search=tag`

I suspect this isn't a bug but rather something I'm doing wrong.  If it makes a difference, the Polymer app is loaded onto a page that before used AngularJS for display and routing, hence the `#/4` hash.  At least for now we cannot change the hash routing system to a path system.

**Update 1:** I believe I need to use the `url-space-regex` in `<iron-location>` but it doesn't seem to be working either.  I tried defining it as a string:

    <iron-location path="{{path}}" hash="{{hash}}" url-space-regex="myPage"></iron-location>

and as a property:

    <iron-location path="{{path}}" hash="{{hash}}" url-space-regex="{{appRegex}}"></iron-location>

    ...

    properties: {
        appRegex: {
          type: String,
          value: "myPage"
        },
    }

**Update 2:** Debugging `<iron-location>` it appears that on line 199 `newUrl` is equal to `currentUrl` causing no navigation to occur.  For some reason `<iron-location>`'s URL is being set after the browser's URL is set.

      var newUrl = this._getUrl();
      var currentUrl = (
          window.location.pathname +
          window.location.search +
          window.location.hash
      );
      if (newUrl == currentUrl) { // these are equal at this point
        // nothing to do, the URL didn't change
        return; // the function returns without navigating
      }

### Expected outcome

The browser navigates properly when any link is clicked.

### Actual outcome

The URL is modified to include the link text but the browser does not navigate.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by intcreatorlds** [comment]
I found the solution.  I needed to include `use-hash-as-path` in `<app-location>`, not in a separate `<iron-location>` tag.  It's possible the two were conflicting.  Because `<app-location>` contains an `<iron-location>` element, it is redundant to include both in an element for routing.

**Comment by rictic** [comment]
It looks like you've tracked this down, but each iron-location and app-location are independent, so any configuration you need for one about the url space would need to be put into all of them.
