### ISSUE TITLE
window.location.href not triggering routepagechanged

### ISSUE THREAD

**Issue by hamzaislam** [PolymerElements/app-route#131]
Using an anchor tag in my page and clicking on it changes the url which in turn triggers the route changed observer function. Where anchor href is "mypath"

Using this.set(route.path, "mypath"); works too

Doing the same thing using window.location.href = "mypath" doesnt work and i get a navigated to mypath message in my console and eventually a 404. 

Sorry if not much samples yet typing this from my phone.

**Comment by rictic** [comment]
This is intended. We don't want to intercept any browser APIs if there is an existing and supported way in the web platform to do something. To navigate to "mypath" from javascript simply do:

```javascript
window.history.pushState({}, null, 'mypath');
window.dispatchEvent(new CustomEvent('location-changed'));
```

The first line updates the URL and the second sends an event letting interested observers know. (There is no specced event for a URL update like this, so we just use `location-changed`).

Philosophically, we try to use native browser APIs whenever possible. The only reason we intercept clicks on anchor tags is that there's no other way to get proper anchor functionality.

**Comment by akc42** [comment]
@ritic I just found that the little snippet doesn't work properly.  I think you gave it to me elsewhere in the issues but I can't find it.  However,  I was using the above snippet to switch my path and it wasn't switching.  I think its because it needs a micro.tick to update window.location.pathname. and iron-location (which handles this event) seems to receive the value before the new value has been updated.

I solved it by doing the following

```
      window.history.pushState({}, null, this.generateUri(path,params));
      this.async(function() {
        window.dispatchEvent(new CustomEvent('location-changed'));
      });
```

**Comment by rictic** [comment]
Hm. The iron-location must have been attached to the document and had its `attached` method run. Once that has happened then the `this.async` isn't necessary.

To double check this, try it out on the demo page here: https://elements.polymer-project.org/mypath

When I paste this into the chrome devtools both the url bar and the paper input change to reflect the new path:

```javascript
window.history.pushState({}, null, '/mypath');
window.dispatchEvent(new CustomEvent('location-changed'));
```

You can also try to come up with a repro for your issue, starting with something like this: https://jsbin.com/lebawa/edit?html,output
