### ISSUE TITLE
Question: FirebaseAuth & App-Route

### ISSUE THREAD

**Issue by JGSolutions** [PolymerElements/app-route#133]
I need to authenticate certain pages in an app and I am not sure how to do this with firebase-auth.

What I need to do is wait until initial response from firebase-auth then execute the app-route depending if there is an authenticated object.

**Comment by ansarizafar** [comment]
Is there any recommended solution from Polymer team?

**Comment by TimvdLippe** [comment]
You can write a custom wrapper/deocrator to achieve this. This decorator takes as argument the auth object. Inside the decorator you define a domif that stamps its content. E.g.
```
<template is="dom-if" if="[[isAllowedToViewPage(auth)]]">
  <content></content>
</template>
```

(I am not a member of the Polymer team)

**Comment by JGSolutions** [comment]
@TimvdLippe Thanks for the response.

The issue is when you refresh the app which firebase auth execution is asynchronous so the auth argument will be empty then eventually the auth will contain an object if the user is authenticated. 

But in the meantime when the auth is empty how do i handle this?

**Comment by TimvdLippe** [comment]
In that case the computed method has not been triggered yet. Therefore the dom-if will not stamp the content and nothing is shown on screen. You can add another dom-if with the negated value, which shows a placeholder. An example of this approach is here: https://github.com/AreaFiftyLAN/lancie-frontend/blob/master/app/elements/lancie-login/lancie-login-check.html

**Comment by JGSolutions** [comment]
ok thanks...i will try this for sure :)

**Comment by esd100** [comment]
I am wondering about this as well. Is there an official Polymer recommendation?
