### ISSUE TITLE
No closing element for flickr-image-page on line 46 of flickr-search-demo.html

### ISSUE THREAD

**Issue by SilverPaladin** [PolymerElements/app-route#143]
On line 46 of the following page `https://github.com/PolymerElements/app-route/blob/master/demo/data-loading-demo/flickr-search-demo.html` there should be a closing tag `</flickr-image-page>` instead there is a closing tag `</flickr-search-page>`

**Comment by rictic** [comment]
Oh, good catch! Want to send a PR to fix? 😀

**Comment by rictic** [comment]
Fixed in #145
