### ISSUE TITLE
Question: How to use app-route to redirect path (i.e. upon successful sign-in)

### ISSUE THREAD

**Issue by andrewspy** [PolymerElements/app-route#150]
What's the best way to use `app-route`/`app-location` to redirect to different path? Shall I just use `window.location` directly? i.e. `firebase-auth` code below:-

```javascript
...
signIn: function() {
  this.$.auth.signInWithPopup()
    .then(function (response) {
      window.location = '/'; // XXX: Redirect upon success
//            window.history.pushState({}, null, '/');
//            window.dispatchEvent(new CustomEvent('location-changed'));
    });
},
...
```

**Comment by TimvdLippe** [comment]
I prefer to use a simple wrapper which does the check. In your `iron-pages` use something like

```html
<iron-pages attr-for-selected="data-route" selected="{{route}}">
  <div data-route="home">
    <home-page></home-page>
  </div>
  <div data-route="my-area">
    <login-check user="{{user}}">
      <my-area user="{{user}}"></my-area>
    </login-check>
  </div>
</iron-pages>
```

And `login-check` is a wrapper which does:

```html
<template>
  <template is="dom-if" if="{{exists(user)}}" restamp="true">
    <content></content>
  </template>
  <template is="dom-if" if="{{!exists(user)}}">
    <login-form on-logged-in="storeUser"></login-form>
  </template>
</template>
```

This makes routing composable without redirecting 😄

**Comment by andrewspy** [comment]
Shouldn't `app-route` provide a API for redirection? or is it not advisable to have a redirection in SPA?

**Comment by TimvdLippe** [comment]
I would personally advise against redirection. It was an old pattern ot MPA since these would not know what to do, but in a SPA you actually know what to do and do not want to punish a user with a redirect. It is costly for no benefit :)

**Comment by akc42** [comment]
I solve this issue by having two elements below `<my-app>` - A bit like so

```
<my-app>
  <my-session user="{{user}}" is-logged-in="{{isLoggedIn}}" hidden$="{{isLoggedIn}}></my-session>
  <my-pages user="{{user}}" hidden$="{{!isLoggedIn}}">
   <app-location route="{{route}}"></app-location>
  <app-route="{{route}} ...
 </my-pages
<my-app>
```
That way any logging in is outside of the url structure.  My rationale is that the real reason for having a router is to expose urls to the user, who might use them copy and paste to someone else to access a particular part of the application.  If that some else is not logged in, then I want them to be able to do that without changing the url

**Comment by andrewspy** [comment]
I understand the part on using a composable  element for login, but there are instances where the  web app needs to be redirected to different section/part of the app to make it more user friendly, and it would be great to have an API for that purpose. Shall this be a feature request?

**Comment by akc42** [comment]
You can easily switch path to a completely different url by doing the following

```
        window.history.pushState({}, null, '/a_new_url');
        window.dispatchEvent(new CustomEvent('location-changed'));
```

I generally do the above when its in a way different part of the tree, or I adjust my `route.path` for local changes.  If I need to know the return address, I normally write it into a `return` query parameter.

**Comment by andrewspy** [comment]
@akc42 I am new to javascript's promise, does it mean that there is no way to access `route.path` inside the promise returned by `signInWithPopup()`?

**Comment by andrewspy** [comment]
@ack42 I managed to do the following:-

```javascript
...
signIn: function() {
  this.$.auth.signInWithPopup()
    .then(function (response) {
      // Redirect upon success
      app = this.document.querySelector('my-app');
      app.set('route.path', '/');
    });
},
...
```

I shall close the issue. Thanks!

**Comment by JGSolutions** [comment]
@TimvdLippe Your example does not work as expected. I want to wrap your example <login-check> only on certain views then needs to be authenticated but even if I am not in that specific route the login-check gets executed and logs out all my views. Also since I am using the prpl pattern makes things abit more complex

Has been another other solutions. Is the polymer team gonna implement some auth-route component?

**Comment by JGSolutions** [comment]
Ok i cam up with something and paste the code in jsbin soon
