### ISSUE TITLE
Infinite loop with version 0.9.3

### ISSUE THREAD

**Issue by n4ttila** [PolymerElements/app-route#157]
### Description

The 0.9.3 'app-route' generates infinite loop. (0.9.2. worked fine)

Code example:

    <app-location route="{{route}}" use-hash-as-path></app-location>
    <app-route route="{{route}}" pattern="/:page" data="{{routeData}}"></app-route>

![app-route issue](https://cloud.githubusercontent.com/assets/22800786/20169004/b4f91eda-a72d-11e6-9e69-b0d61bbf90fc.png)

**Comment by joryphillips** [comment]
Not sure if related, but I'm seeing this in 0.9.2 when a single quote mark (%27) gets added to queryParams.

**Comment by butterandfly** [comment]
I got this too, but the version of app-route is 0.9.2. My chrome's version is 54.
