### ISSUE TITLE
bower update with #2.0-preview fails due to missing polymer branch

### ISSUE THREAD

**Issue by TomK** [PolymerElements/app-route#170]
app-route `2.0-preview` depends on polymer branch `2.0-data-updates`, but that branch was deleted when Polymer/polymer#4221 was merged.

A PR to update dependency back to `2.0-preview` is here https://github.com/PolymerElements/app-route/pull/169

**Comment by TomK** [comment]
@e111077 I saw you originally specified the data updates branch here https://github.com/PolymerElements/app-route/commit/57f5868f483cd56c1492409c978065610d3ac273. Would you mind taking a look at this PR please?

**Comment by e111077** [comment]
I flubbed the commit message but here it is https://github.com/PolymerElements/app-route/commit/dafcc0aa78407483ea10e66005029a6382d2dcca
