### ISSUE TITLE
app-location fires 'route-changed' event twice on a single route change

### ISSUE THREAD

**Issue by mkropf** [PolymerElements/app-route#173]
### Description
Example usage:

    <dom-module id="client-component">
      <template>
        <app-location id="loc" route="{{_route}}" use-hash-as-path></app-location>
        <p><a href="#test">test</a></p>
      </template>
      <script>
        window.addEventListener('WebComponentsReady',function(){Polymer({
          is: 'client-component',
          ready: function(){
            this.$.loc.addEventListener('route-changed',function(e){
              console.log(e.detail)
            });
          }
        })});
      </script>
    </dom-module>

### Expected outcome
Clicking the link or changing the browser address should log a single event.

### Actual outcome
The event is fired twice.

### Analysis
Finding the cause in debugger showed that the property-changed effect is registered twice and therefore triggered twice when the route property changed. The cause for the duplicated effect registration is the fact that app-location declares the 'route' property and has the AppRouteConverterBehavior, which in turn also declares the 'route' property. (You may see it as a app-location bug or as polymer core bug)

**Comment by Niklas2908** [comment]
So is there any solution to prevent app-location from firing a second time? Or a way to listen only to the first call ?

**Comment by dwalker0044** [comment]
Related/duplicated: https://github.com/PolymerElements/app-route/issues/178

**Comment by Retlawxx** [comment]
For me, this happens only when the path has parameters like `/path?parameter=test`

**Comment by tjb1982** [comment]
I'm experiencing something similar to what @lauritowal mentioned above: when there _were_ `queryParams` before changing the URL to something without query params, then `route-changed` is dispatched twice, the first time around with bad state (i.e., the old `queryParams`).

E.g., start with URL:

    /context/?param=foo

`route-changed` is dispatched:

    appRout.queryParams === {param: "foo"}

user clicks on `<a href="/context">...</a>`, and `route-changed` is dispatched:

    appRoute.queryParams === {param: "foo"}

but then `route-changed` is immediately dispatched a second time:

    appRoute.queryParams === {}

The work-around I'm using is wrapping my `route-changed` event handler in a 0ms-timeout, which allows the event loop to recycle and finish the required mutations to the state of the `queryParams`. However, `route-changed` is still dispatched twice.

**Comment by mkropf** [comment]
outdated, nobody caring anymore

**Comment by danleyb2** [comment]
@mkropf  this issue still exist

**Comment by danleyb2** [comment]
On further testing, it happens when using `url-space-regex` and `pattern`

This fires changed twice
```html
<app-location route="{{route}}" url-space-regex="^[[rootPath]]"></app-location>
<app-route route="{{route}}" pattern="[[rootPath]]:page" data="{{routeData}}" tail="{{subroute}}"></app-route>
```

This fires changed once
```html
 <app-location route="{{route}}"></app-location>
 <app-route route="{{route}}" data="{{routeData}}" tail="{{subroute}}"></app-route>
```
