### ISSUE TITLE
Two data change events when app-routes chained.

### ISSUE THREAD

**Issue by dwalker0044** [PolymerElements/app-route#178]
### Description
Chaining two app routes causes the second to fire two data change events when the route changes.

### Expected outcome

Should only fire once.

### Actual outcome

Fires twice.

### Example code

```
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/paper-button/paper-button.html">
<link rel="import" href="../../bower_components/app-route/app-route.html">
<link rel="import" href="../../bower_components/app=">

<dom-module id="app-route-app">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <h2>app-route bug demo</h2>
    
    <app-route
        route="{{route}}"
        pattern="/:page"
        data={{firstData}}
        tail="{{tail}}">
    </app-route>
    
    <app-route
        route="{{tail}}"
        pattern="/:page"
        data="{{data}}">
    </app-route>
        
    <paper-button raised on-tap="_setRoute">button</paper-button>
    
  </template>

  <script>
    Polymer({

      is: 'app-route-app',

      properties: {
        route: {
          type: Object,
          notify: true,
          value: function() {return {path: "", prefix:""}}
        },
            
        data: {
          type: Object,
          notify: true
        },
        
        firstData: {
          type: Object,
          notify: true
        },
        
        tail: {
          type: Object,
          notify: true
        },
      },
      
      observers: [
        "_onRouteChanged(route.*)",
        "_onFirstDataChanged(firstData.page)",
        "_onDataChanged(data.page)",
        "_onTailChanged(tail.*)"
      ],
      
      _setRoute: function(e) {
//        console.log("Setting route.");
        this.set("route.path", "/some/path/somewhere"); 
      },
      
      _onRouteChanged: function(newValue) {
//        console.log("Route changed: " + JSON.stringify(newValue));
      },
      
      _onDataChanged: function(newValue) {
        console.log("Data page changed: " + JSON.stringify(newValue));
      },
      
      _onFirstDataChanged: function(newValue) {
        console.log("First page changed: " + JSON.stringify(newValue));
      },
      
      _onTailChanged: function(newValue) {
//        console.log("Tail path changed: " + JSON.stringify(newValue));
      },

    });
  </script>
</dom-module>

```

### Steps to reproduce

1. Load the above example (consists of a page with a button that sets the route).
2. Open developer tools and open the console.
3. Clear any output and then click the button.
4. You'll see the output:
```
First page changed: "some"
Data page changed: "path"
Data page changed: "path"
```
One data change for the top level `app-route` and then two events for the chained `app-route`.

### Cause

Seems to be `__tryToMatch` function in app-route.html. Set a break point here before clicking the button, the debugger will stop once for the first app-route, the again for the second app-route. During this function the tail variable gets updated which calls `__tailPathChanged` which does `this.set('route.path', newPath);` which calls `__tryToMatch` for the third time. From what I can tell, `__tryToMatch` doesn't check that the data value has actually changed and we get the second update event - unlike the tail which is checked and so we don't get the second update event.

### Browsers Affected

- [x] Chrome

**Comment by jfrazzano** [comment]
I don’t have an answer, just another related question… In the a link from the dev site on css triggers, the cite is using a modular routing, sans hash to paint segments of the page.  The code is twitter code, and same design code is in a polymer pen on github.  Anyone know how to route like this site: https://csstriggers.com/background-blend-mode <https://csstriggers.com/background-blend-mode>   controlling the paint.

same design on codeine, by eric sans the routing.

https://codepen.io/PolyMaterial/pen/jGucf?editors=0010 <https://codepen.io/PolyMaterial/pen/jGucf?editors=0010>

if anyone knows would love a link.

**Comment by dwalker0044** [comment]
@jfrazzano probably best not to ask that kind of a question in the middle of a bug report. You might have more success in the [polymer slack channel](https://polymer.slack.com/messages/general/)

**Comment by jfrazzano** [comment]
Sorry.  Have just been curious for days.

**Comment by dwalker0044** [comment]
Related/duplicated: https://github.com/PolymerElements/app-route/issues/173

**Comment by e111077** [comment]
duplicate. closing in favor of #173
