### ISSUE TITLE
app-route vs carbon-route naming inconsistency

### ISSUE THREAD

**Issue by gstroup** [PolymerElements/app-route#187]
### Description
Customers are confused since app-route is not available in bower.  Can you please publish this project to bower with the name "app-route"?  (Or perhaps a new name, since that name is already taken in the bower registry.)

### Expected outcome
`bower install app-route`
would install this project.  

### Actual outcome
`bower install app-route` installs another package.
`bower install carbon-route` installs this package

### Steps to reproduce
see above.

### Browsers Affected
All

**Comment by lawrencemok** [comment]
Agree, quite a bit of confusion here as there are many new users to Polymer / Bower that could get stuck

**Comment by abdonrd** [comment]
Polymer doesn't use the bower registry.
You should use `bower install PolymerElements/element-name`.
In this case: `bower install PolymerElements/app-route`.

**Comment by e111077** [comment]
I endorse @abdonrd's answer
