### ISSUE TITLE
app-location removes query params after upgrade from polymer v2.0.0-rc.7 to v2.0.0-rc.8

### ISSUE THREAD

**Issue by jonagh** [PolymerElements/app-route#192]
Not sure if this issue should be here (in app-route) or in the Polymer repo.. but upgrading from Polymer v2.0.0-rc.7 to rc.8 has changed something that causes app-location to remove query params from the URL.

Eg: **example.html?a=1** will be changed to **example.html** (without query params) with Polymer rc.8 (or later). With rc.7 (or before) the URL stays as it should (with the query params).

The below html will cause the issue to occur. If `polymer+v2.0.0-rc.8` is changed to `polymer+v2.0.0-rc.7` then it will work fine.

```
<!doctype html>
<html>
<head>
  <base href="https://polygit.org/polymer+v2.0.0-rc.8/app-route+polymerelements+*/shadydom+webcomponents+:master/shadycss+webcomponents+:master/custom-elements+webcomponents+:master/webcomponentsjs+webcomponents+:master/components/">
  <script src="webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="app-route/app-location.html">
</head>
<body>
  <app-location></app-location>
</body>
</html>
```

**Comment by lastmjs** [comment]
Possible duplicate: https://github.com/PolymerElements/app-route/issues/194

**Comment by lastmjs** [comment]
Looks like there's a PR to fix this: https://github.com/PolymerElements/iron-location/pull/83
