### ISSUE TITLE
app-location doesn't preserve query-string on reload

### ISSUE THREAD

**Issue by fooloomanzoo** [PolymerElements/app-route#194]
The `query`-attribute of the internal `iron-location` gets overwritten on initial load

**Comment by lastmjs** [comment]
I think I'm running into this issue as well. When I put a URL into the browser with a query parameter and hit return, the query parameter disappears. I am using a static file server that rewrites to my index.html file (SPA support), if that makes any difference.

**Comment by lastmjs** [comment]
Possible duplicate: https://github.com/PolymerElements/app-route/issues/192

**Comment by lastmjs** [comment]
Looks like there's a PR to fix this: https://github.com/PolymerElements/iron-location/pull/83

**Comment by fooloomanzoo** [comment]
The Problem lies at the `paramsObj` in `iron-query-params.html`. The `paramsObj `is initialy an empty Object and gets initially parsed and reflected to the `window.location.search` String. A solution could be that the `paramsObj` is `null `in the beginning so that the observer is not called.

**Comment by ronnyroeller** [comment]
Observing the same issue when packing the web app with Cordova: Cordova's cdvToken gets stripped from the URL, thereby preventing device images to be shown in the Cordova app.

**Comment by ernsheong** [comment]
I'm running into this bug as well.

**Comment by SieBrum** [comment]
Still encountering this problem, even on version 2.0.2

**Comment by hyyan** [comment]
still an issue

**Comment by ArthurJahn** [comment]
same problem here

**Comment by e111077** [comment]
fixed by #86

**Comment by ankon** [comment]
@e111077 do you mean #86 is a duplicate, and fixing that would fix this issue? Right now I'm confused as to the state of #194: It's closed by #86, but that one is still open without much activity.

**Comment by e111077** [comment]
Nice catch. I meant to link to another repo. Comment fixed
