### ISSUE TITLE
Changing data.page doesn't update history

### ISSUE THREAD

**Issue by artemik** [PolymerElements/app-route#202]
Suppose have this:

```
    <app-location route="{{route}}"></app-location>
    <app-route
        route="{{route}}"
        pattern="/:page"
        data="{{routeData}}">
    </app-route>
```
Programmatically updating `routeData.page` brings me to a new page, but it doesn't update the browser history.

I know about
```
window.history.pushState({}, null, '/new_path');
window.dispatchEvent(new CustomEvent('location-changed'));
```
but I definitely shouldn't mess around with it manually.

**Comment by ymaz** [comment]
@artemik you could try to update `route` "programmatically"
`this.set(route, '/new_path');`
it should force path update as well as history records.

**Comment by ggirard07** [comment]
route is not a simple string bug rather a complex object.
I don't think you can update it this way without breaking some app-location / app-route internals.

**Comment by ymaz** [comment]
@artemik @ggirard07 
Yes, you are right, that `route` is Object so then you should able to update the `path` prop under this object
`this.set('route.path', '/search/');`
or via
`this.set('routeData.user', 'mary');`
^^
https://www.polymer-project.org/1.0/toolbox/routing#change-routes

**Comment by hariprasadiit** [comment]
bug is still present. changes to the `data` are not propagating to the `route` object.

**Comment by e111077** [comment]
Cannot reproduce. Please reopen with a live code example. Please see our issue template:

https://raw.githubusercontent.com/PolymerElements/app-route/master/.github/ISSUE_TEMPLATE.md
