### ISSUE TITLE
app-location.html, app-router-converter-behavior.html, app-route-converter.html etc files are missing after bower install

### ISSUE THREAD

**Issue by saadixl** [PolymerElements/app-route#215]
### Description

I tried to install ```app-route``` using ```bower install app-route --save``` on ```Polymer 1.9.1```. After installation I found out that, app-location.html, app-router-converter-behavior.html, app-route-converter.html etc files are missing under ```/bower_components/app-route```.

### Expected outcome
Expected all the missing files inside the directory

### Actual outcome
app-location.html, app-router-converter-behavior.html, app-route-converter.html etc files were missing

### Steps to reproduce
- On Polymer 1.9.1, ```bower install app-route --save```
- Check ```bower_components```

**Comment by ernsheong** [comment]
Have you tried clearing out your `bower_components` folder and retrying?

**Comment by saadixl** [comment]
Yeah I removed the ```bower_components``` and tried again. But didn't work. Screenshot attached:

<img width="310" alt="screen shot 2017-10-15 at 8 31 40 pm" src="https://user-images.githubusercontent.com/1633940/31585705-26a472c6-b1e8-11e7-8ce5-b4c2fe5aef3d.png">

**Comment by ernsheong** [comment]
The latest release of bower is 1.8.2. Check with `bower --version` and make sure you have the latest version. Update with `npm i -g bower`

In the meantime, you can download the release manually from https://github.com/PolymerElements/app-route/releases and get on with life.

**Comment by NeilujD** [comment]
@saadixl I think you should install this element via `bower install --save PolymerElements/app-route` command instead and remove the line `"app-route": "^[version]"`, in you `bower.json` file.

**Comment by saadixl** [comment]
```bower install --save PolymerElements/app-route``` worked. Thanks for helping 🙂
