### ISSUE TITLE
Any way to override iron-location's dwellTime?

### ISSUE THREAD

**Issue by chajath** [PolymerElements/app-route#217]
### Description
Sometimes, when navigation is initiated by `this.set("route.path", ...)`, current location is not recorded in browser nav stack if the navigation is made under the default dwell time of 2 seconds.

### Expected outcome
A way to override default dwell time behavior.

### Actual outcome
No viable alternative to sticking to the default dwell time, or firing navigation event to `window`.

**Comment by chajath** [comment]
I see there are at least three PRs to add this: #135, #184, #213

Could any of polymer team look at them and merge the PR please?

**Comment by aarondrabeck** [comment]
+1

**Comment by e111077** [comment]
revived and merged #135
