### ISSUE TITLE
Tests sometimes time out

### ISSUE THREAD

**Issue by rictic** [PolymerElements/app-route#64]
We get a message in the iframe saying that it can't find the path /foo/, suggesting that the page reloaded/redirected during testing.

I've only seen this failure in Chrome.

**Comment by e111077** [comment]
Can confirm this also happens locally sometimes on IE11 and MS Edge

**Comment by TimvdLippe** [comment]
I started debugging these timeouts here: https://github.com/TimvdLippe/carbon-route/pull/1

**Comment by TimvdLippe** [comment]
[This regex](https://github.com/PolymerElements/carbon-route/blob/master/test/carbon-location.html#L174) appears to break it. You can see the builds in my PR where commenting the regex fixes the timeout.

**Comment by TimvdLippe** [comment]
Has been fixed in #95, my PR tests ran cleanly.

**Comment by cdata** [comment]
Thanks @TimvdLippe. I'm going to close this until someone suggests it is still a bug.
